# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

#trigger:
#  branches:
#    include:
#    - master

#pool:
#  name: GB BIM Local
#  demands: npm

#steps:
#- task: Npm@1
#  displayName: 'npm install'
#  inputs:
#    workingDir: 'gb-base-app'
#    verbose: false

#- task: Npm@1
#  displayName: 'npm build'
#  inputs:
#    command: custom
#    workingDir: 'gb-base-app'
#    verbose: false
#    customCommand: 'run build -- --prod'

#- task: AzureRmWebAppDeployment@4
#  displayName: 'Azure App Service Deploy: gbbaseapp'
#  inputs:
#    azureSubscription: 'ERP-Development (3a20b8fe-ead8-4f71-ad09-146249810656)'
#    WebAppName: gbbaseapp
#    deployToSlotOrASE: true
#    ResourceGroupName: 'az-bim-dev'
#    packageForLinux: '$(System.DefaultWorkingDirectory)/gb-base-app/dist/gb-base-app'